[package]
name = "argent-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
argent-artifact = { workspace = true }
blake2b_simd = { workspace = true }
blake3 = { workspace = true }
kaspa-consensus-core = { workspace = true }
kaspa-txscript = { workspace = true }
kaspa-txscript-errors = { workspace = true }
silverscript-abi = { workspace = true }
thiserror = { workspace = true }
