[package]
name = "argent-artifact"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blake2b_simd = { workspace = true }
blake3 = { workspace = true }
faster-hex = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
silverscript-abi = { workspace = true }
thiserror = { workspace = true }
